export const errorMessages: Record<string, string> = {
  'Not authorized to perform this action': 'Không có quyền thực hiện hành động này.',
  'Email already exists': 'Email đã tồn tại. Vui lòng chọn email khác.',
  'Invalid phone number': 'Số điện thoại không hợp lệ. Vui lòng kiểm tra lại.',
  'Please provide name, email and password': 'Vui lòng nhập đầy đủ thông tin.',
  'Please provide email and password': 'Vui lòng nhập email và mật khẩu.',
  'Invalid credentials': 'Thông tin đăng nhập không chính xác.',
  'Please login with Google': 'Vui lòng đăng nhập bằng Google.',
  'User is not active': 'Tài khoản chưa được kích hoạt.',
  'User not found': 'Tài khoản không tồn tại.',
  'Please provide name and phone number': 'Vui lòng nhập tên và số điện thoại.',
  'Please provide current password and new password': 'Vui lòng nhập mật khẩu hiện tại và mật khẩu mới.',
  'Invalid current password': 'Mật khẩu hiện tại không chính xác.',
  'Please provide productId': 'Vui lòng nhập productId.',
  'Product already in wishlist': 'Sản phẩm đã có trong danh sách yêu thích.',
  'Category name is required': 'Vui lòng nhập tên danh mục.',
  'Category ID is required': 'Vui lòng nhập ID danh mục.',
  'Category not found': 'Danh mục không tồn tại.',
  'Category has products, cannot delete': 'Danh mục đã có sản phẩm, không thể xóa.',
  'Product not found': 'Sản phẩm không tồn tại.'
}
